version: '3.4'

services:
  portfoliobeta:
    image: portfoliobeta
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 5000:5000
